from ..utils import *


def clear_custom_data(did):
    if not askUser(
        """Clear custom data in all cards?
    The custom scheduling of FSRS4Anki stored memory state in custom data.
    It is unused when you enable the built-in FSRS.
    Are you sure?"""
    ):
        return

    cards = mw.col.db.list(
        """
            SELECT id
            FROM cards
            WHERE data != '' 
            AND json_extract(data, '$.cd') IS NOT NULL
        """
    )

    cnt = 0
    reset_cards = []
    start_time = time.time()
    undo_entry = mw.col.add_custom_undo_entry("Clear custom data")
    for cid in cards:
        card = mw.col.get_card(cid)
        card.custom_data = ""
        reset_cards.append(card)
        cnt += 1

    mw.col.update_cards(reset_cards)
    mw.col.merge_undo_entries(undo_entry)
    tooltip(f"""{cnt} cards cleared in {time.time() - start_time:.2f} seconds.""")
    mw.reset()


def clear_manual_rescheduling(did):
    if not ask_one_way_sync():
        return

    if not askUser(
        "<p>Clear review logs generated by <b>Reschedule cards on change</b>?</p>"
        + "<p>Due to technical limitations, FSRS Helper cannot distinguish among cards rescheduled by following operations:</p>"
        + "<ul><li>Set due date</li><li>'Reschedule cards on change' in FSRS section of Deck Options</li></ul>"
        + "<p>If you choose to clear, all review logs generated by the above operations will be deleted.</p>"
        + "<p>This action cannot be <b>undone</b>.</p>"
        + "<p>Are you sure?</p>"
    ):
        return
    mw.col.db.all("DELETE FROM revlog WHERE ease = 0 AND factor != 0")
    col_set_modified()
    tooltip("Review logs cleared.")
    mw.reset()
